services:
  app:
    image: hello-front-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app:z
    ports:
      - 3210:5173
    container_name: hello-front-dev

  debug-helper:
    image: busybox
  
  nginx:
    image: nginx:1.29.4
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app